// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hyhvltqvntduthizalmz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5aHZsdHF2bnRkdXRoaXphbG16Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIwNDM2NzUsImV4cCI6MjA3NzYxOTY3NX0.mh81WYgA6QXcSFaWA8v8u0ujVbaEDjTv3w-j9MGrZJw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});